package com.eglobal.gefa.model;
// Generated 1/07/2018 09:11:29 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * GefaFactory generated by hbm2java
 */
public class GefaFactory implements java.io.Serializable {

	private String idFactory;
	private String factoryName;
	private Set gefaUserses = new HashSet(0);

	public GefaFactory() {
	}

	public GefaFactory(String idFactory) {
		this.idFactory = idFactory;
	}

	public GefaFactory(String idFactory, String factoryName, Set gefaUserses) {
		this.idFactory = idFactory;
		this.factoryName = factoryName;
		this.gefaUserses = gefaUserses;
	}

	public String getIdFactory() {
		return this.idFactory;
	}

	public void setIdFactory(String idFactory) {
		this.idFactory = idFactory;
	}

	public String getFactoryName() {
		return this.factoryName;
	}

	public void setFactoryName(String factoryName) {
		this.factoryName = factoryName;
	}

	public Set getGefaUserses() {
		return this.gefaUserses;
	}

	public void setGefaUserses(Set gefaUserses) {
		this.gefaUserses = gefaUserses;
	}

}
