package com.eglobal.gefa.model;
// Generated 4/07/2018 10:11:17 AM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * GefaFactory generated by hbm2java
 */
public class GefaFactory implements java.io.Serializable {

	private String idFactory;
	private String factoryName;
	private Set gefaUsers = new HashSet(0);

	public GefaFactory() {
	}

	public GefaFactory(String idFactory) {
		this.idFactory = idFactory;
	}

	public GefaFactory(String idFactory, String factoryName, Set gefaUsers) {
		this.idFactory = idFactory;
		this.factoryName = factoryName;
		this.gefaUsers = gefaUsers;
	}

	public String getIdFactory() {
		return this.idFactory;
	}

	public void setIdFactory(String idFactory) {
		this.idFactory = idFactory;
	}

	public String getFactoryName() {
		return this.factoryName;
	}

	public void setFactoryName(String factoryName) {
		this.factoryName = factoryName;
	}

	public Set getGefaUsers() {
		return this.gefaUsers;
	}

	public void setGefaUsers(Set gefaUsers) {
		this.gefaUsers = gefaUsers;
	}

}
