package com.eglobal.gefa.model;
// Generated 1/07/2018 09:11:29 PM by Hibernate Tools 5.0.6.Final

/**
 * GefaUsers generated by hbm2java
 */
public class GefaUsers implements java.io.Serializable {

	private GefaUsersId id;
	private GefaFactory gefaFactory;
	private GefaRole gefaRole;

	public GefaUsers() {
	}

	public GefaUsers(GefaUsersId id) {
		this.id = id;
	}

	public GefaUsers(GefaUsersId id, GefaFactory gefaFactory, GefaRole gefaRole) {
		this.id = id;
		this.gefaFactory = gefaFactory;
		this.gefaRole = gefaRole;
	}

	public GefaUsersId getId() {
		return this.id;
	}

	public void setId(GefaUsersId id) {
		this.id = id;
	}

	public GefaFactory getGefaFactory() {
		return this.gefaFactory;
	}

	public void setGefaFactory(GefaFactory gefaFactory) {
		this.gefaFactory = gefaFactory;
	}

	public GefaRole getGefaRole() {
		return this.gefaRole;
	}

	public void setGefaRole(GefaRole gefaRole) {
		this.gefaRole = gefaRole;
	}

}
