package com.eglobal.gefa.model;
// Generated 1/07/2018 09:11:29 PM by Hibernate Tools 5.0.6.Final

/**
 * GefaUsersId generated by hbm2java
 */
public class GefaUsersId implements java.io.Serializable {

	private String username;
	private String surname;
	private String name;
	private String email;
	private String telephone;
	private String idRole;
	private String idFactory;

	public GefaUsersId() {
	}

	public GefaUsersId(String username, String surname, String name, String email, String telephone, String idRole,
			String idFactory) {
		this.username = username;
		this.surname = surname;
		this.name = name;
		this.email = email;
		this.telephone = telephone;
		this.idRole = idRole;
		this.idFactory = idFactory;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public String getIdRole() {
		return this.idRole;
	}

	public void setIdRole(String idRole) {
		this.idRole = idRole;
	}

	public String getIdFactory() {
		return this.idFactory;
	}

	public void setIdFactory(String idFactory) {
		this.idFactory = idFactory;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GefaUsersId))
			return false;
		GefaUsersId castOther = (GefaUsersId) other;

		return ((this.getUsername() == castOther.getUsername()) || (this.getUsername() != null
				&& castOther.getUsername() != null && this.getUsername().equals(castOther.getUsername())))
				&& ((this.getSurname() == castOther.getSurname()) || (this.getSurname() != null
						&& castOther.getSurname() != null && this.getSurname().equals(castOther.getSurname())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
						&& this.getName().equals(castOther.getName())))
				&& ((this.getEmail() == castOther.getEmail()) || (this.getEmail() != null
						&& castOther.getEmail() != null && this.getEmail().equals(castOther.getEmail())))
				&& ((this.getTelephone() == castOther.getTelephone()) || (this.getTelephone() != null
						&& castOther.getTelephone() != null && this.getTelephone().equals(castOther.getTelephone())))
				&& ((this.getIdRole() == castOther.getIdRole()) || (this.getIdRole() != null
						&& castOther.getIdRole() != null && this.getIdRole().equals(castOther.getIdRole())))
				&& ((this.getIdFactory() == castOther.getIdFactory()) || (this.getIdFactory() != null
						&& castOther.getIdFactory() != null && this.getIdFactory().equals(castOther.getIdFactory())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUsername() == null ? 0 : this.getUsername().hashCode());
		result = 37 * result + (getSurname() == null ? 0 : this.getSurname().hashCode());
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (getEmail() == null ? 0 : this.getEmail().hashCode());
		result = 37 * result + (getTelephone() == null ? 0 : this.getTelephone().hashCode());
		result = 37 * result + (getIdRole() == null ? 0 : this.getIdRole().hashCode());
		result = 37 * result + (getIdFactory() == null ? 0 : this.getIdFactory().hashCode());
		return result;
	}

}
