package com.eglobal.gefa.model;
// Generated 25/07/2018 08:37:44 PM by Hibernate Tools 5.0.6.Final

/**
 * GefaIncidenceId generated by hbm2java
 */
public class GefaIncidenceId implements java.io.Serializable {

	private String workOrderId;
	private int incidenceId;

	public GefaIncidenceId() {
	}

	public GefaIncidenceId(String workOrderId, int incidenceId) {
		this.workOrderId = workOrderId;
		this.incidenceId = incidenceId;
	}

	public String getWorkOrderId() {
		return this.workOrderId;
	}

	public void setWorkOrderId(String workOrderId) {
		this.workOrderId = workOrderId;
	}

	public int getIncidenceId() {
		return this.incidenceId;
	}

	public void setIncidenceId(int incidenceId) {
		this.incidenceId = incidenceId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GefaIncidenceId))
			return false;
		GefaIncidenceId castOther = (GefaIncidenceId) other;

		return ((this.getWorkOrderId() == castOther.getWorkOrderId()) || (this.getWorkOrderId() != null
				&& castOther.getWorkOrderId() != null && this.getWorkOrderId().equals(castOther.getWorkOrderId())))
				&& (this.getIncidenceId() == castOther.getIncidenceId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getWorkOrderId() == null ? 0 : this.getWorkOrderId().hashCode());
		result = 37 * result + this.getIncidenceId();
		return result;
	}

}
