package com.eglobal.gefa.model;
// Generated 1/07/2018 09:11:29 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * GefaRole generated by hbm2java
 */
public class GefaRole implements java.io.Serializable {

	private String idRole;
	private String roleName;
	private Set gefaUserses = new HashSet(0);

	public GefaRole() {
	}

	public GefaRole(String idRole) {
		this.idRole = idRole;
	}

	public GefaRole(String idRole, String roleName, Set gefaUserses) {
		this.idRole = idRole;
		this.roleName = roleName;
		this.gefaUserses = gefaUserses;
	}

	public String getIdRole() {
		return this.idRole;
	}

	public void setIdRole(String idRole) {
		this.idRole = idRole;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public Set getGefaUserses() {
		return this.gefaUserses;
	}

	public void setGefaUserses(Set gefaUserses) {
		this.gefaUserses = gefaUserses;
	}

}
