package com.eglobal.gefa.model;
// Generated 25/07/2018 08:37:44 PM by Hibernate Tools 5.0.6.Final

/**
 * GefaModificationId generated by hbm2java
 */
public class GefaModificationId implements java.io.Serializable {

	private String workOrderId;
	private int modificationId;

	public GefaModificationId() {
	}

	public GefaModificationId(String workOrderId, int modificationId) {
		this.workOrderId = workOrderId;
		this.modificationId = modificationId;
	}

	public String getWorkOrderId() {
		return this.workOrderId;
	}

	public void setWorkOrderId(String workOrderId) {
		this.workOrderId = workOrderId;
	}

	public int getModificationId() {
		return this.modificationId;
	}

	public void setModificationId(int modificationId) {
		this.modificationId = modificationId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GefaModificationId))
			return false;
		GefaModificationId castOther = (GefaModificationId) other;

		return ((this.getWorkOrderId() == castOther.getWorkOrderId()) || (this.getWorkOrderId() != null
				&& castOther.getWorkOrderId() != null && this.getWorkOrderId().equals(castOther.getWorkOrderId())))
				&& (this.getModificationId() == castOther.getModificationId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getWorkOrderId() == null ? 0 : this.getWorkOrderId().hashCode());
		result = 37 * result + this.getModificationId();
		return result;
	}

}
