package com.eglobal.gefa.model;
// Generated 25/07/2018 08:37:44 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * GefaPlatform generated by hbm2java
 */
public class GefaPlatform implements java.io.Serializable {

	private String platformId;
	private String name;
	private Set gefaWorkOrders = new HashSet(0);

	public GefaPlatform() {
	}

	public GefaPlatform(String platformId) {
		this.platformId = platformId;
	}

	public GefaPlatform(String platformId, String name, Set gefaWorkOrders) {
		this.platformId = platformId;
		this.name = name;
		this.gefaWorkOrders = gefaWorkOrders;
	}

	public String getPlatformId() {
		return this.platformId;
	}

	public void setPlatformId(String platformId) {
		this.platformId = platformId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getGefaWorkOrders() {
		return this.gefaWorkOrders;
	}

	public void setGefaWorkOrders(Set gefaWorkOrders) {
		this.gefaWorkOrders = gefaWorkOrders;
	}

}
