package com.eglobal.gefa.model;
// Generated 25/07/2018 08:37:44 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * GefaWorkOrder generated by hbm2java
 */
public class GefaWorkOrder implements java.io.Serializable {

	private String workOrderId;
	private GefaFactory gefaFactory;
	private GefaPlatform gefaPlatform;
	private String name;
	private Integer hours;
	private String status;
	private Date startDate;
	private Date finishDate;
	private Date creationDate;
	private Date lastUpdateDate;
	private String complexity;
	private Double rate;
	private Set gefaQuestions = new HashSet(0);
	private Set gefaModifications = new HashSet(0);
	private Set gefaIncidences = new HashSet(0);

	public GefaWorkOrder() {
	}

	public GefaWorkOrder(String workOrderId, GefaFactory gefaFactory, GefaPlatform gefaPlatform) {
		this.workOrderId = workOrderId;
		this.gefaFactory = gefaFactory;
		this.gefaPlatform = gefaPlatform;
	}

	public GefaWorkOrder(String workOrderId, GefaFactory gefaFactory, GefaPlatform gefaPlatform, String name,
			Integer hours, String status, Date startDate, Date finishDate, Date creationDate, Date lastUpdateDate,
			String complexity, Double rate, Set gefaQuestions, Set gefaModifications, Set gefaIncidences) {
		this.workOrderId = workOrderId;
		this.gefaFactory = gefaFactory;
		this.gefaPlatform = gefaPlatform;
		this.name = name;
		this.hours = hours;
		this.status = status;
		this.startDate = startDate;
		this.finishDate = finishDate;
		this.creationDate = creationDate;
		this.lastUpdateDate = lastUpdateDate;
		this.complexity = complexity;
		this.rate = rate;
		this.gefaQuestions = gefaQuestions;
		this.gefaModifications = gefaModifications;
		this.gefaIncidences = gefaIncidences;
	}

	public String getWorkOrderId() {
		return this.workOrderId;
	}

	public void setWorkOrderId(String workOrderId) {
		this.workOrderId = workOrderId;
	}

	public GefaFactory getGefaFactory() {
		return this.gefaFactory;
	}

	public void setGefaFactory(GefaFactory gefaFactory) {
		this.gefaFactory = gefaFactory;
	}

	public GefaPlatform getGefaPlatform() {
		return this.gefaPlatform;
	}

	public void setGefaPlatform(GefaPlatform gefaPlatform) {
		this.gefaPlatform = gefaPlatform;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getHours() {
		return this.hours;
	}

	public void setHours(Integer hours) {
		this.hours = hours;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getFinishDate() {
		return this.finishDate;
	}

	public void setFinishDate(Date finishDate) {
		this.finishDate = finishDate;
	}

	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public Date getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

	public String getComplexity() {
		return this.complexity;
	}

	public void setComplexity(String complexity) {
		this.complexity = complexity;
	}

	public Double getRate() {
		return this.rate;
	}

	public void setRate(Double rate) {
		this.rate = rate;
	}

	public Set getGefaQuestions() {
		return this.gefaQuestions;
	}

	public void setGefaQuestions(Set gefaQuestions) {
		this.gefaQuestions = gefaQuestions;
	}

	public Set getGefaModifications() {
		return this.gefaModifications;
	}

	public void setGefaModifications(Set gefaModifications) {
		this.gefaModifications = gefaModifications;
	}

	public Set getGefaIncidences() {
		return this.gefaIncidences;
	}

	public void setGefaIncidences(Set gefaIncidences) {
		this.gefaIncidences = gefaIncidences;
	}

}
