package com.eglobal.gefa.model;
// Generated 25/07/2018 08:37:44 PM by Hibernate Tools 5.0.6.Final


import java.util.Date;

/**
 * GefaUser generated by hbm2java
 */
public class GefaUser  implements java.io.Serializable {


     private String userId;
     private GefaFactory gefaFactory;
     private GefaRole gefaRole;
     private String name;
     private String surname;
     private Date creationDate;
     private Date lastUpdateDate;
     private String password;
     private String status;
     private byte[] image;
     private String email;
     private String telephone;

    /**
	 * @return the telephone
	 */
	public String getTelephone() {
		return telephone;
	}


	/**
	 * @param telephone the telephone to set
	 */
	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}


	/**
	 * @return the email
	 */
	public String getEmail() {
		return email;
	}


	/**
	 * @param email the email to set
	 */
	public void setEmail(String email) {
		this.email = email;
	}


	public GefaUser() {
    }

	
    public GefaUser(String userId, GefaFactory gefaFactory, GefaRole gefaRole) {
        this.userId = userId;
        this.gefaFactory = gefaFactory;
        this.gefaRole = gefaRole;
    }
   
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public GefaFactory getGefaFactory() {
        return this.gefaFactory;
    }
    
    public void setGefaFactory(GefaFactory gefaFactory) {
        this.gefaFactory = gefaFactory;
    }
    public GefaRole getGefaRole() {
        return this.gefaRole;
    }
    
    public void setGefaRole(GefaRole gefaRole) {
        this.gefaRole = gefaRole;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public Date getLastUpdateDate() {
        return this.lastUpdateDate;
    }
    
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public byte[] getImage() {
        return this.image;
    }
    
    public void setImage(byte[] image) {
        this.image = image;
    }




}


