package com.eglobal.gefa.model;
// Generated 25/07/2018 08:37:44 PM by Hibernate Tools 5.0.6.Final

/**
 * GefaIncidence generated by hbm2java
 */
public class GefaIncidence implements java.io.Serializable {

	private GefaIncidenceId id;
	private GefaWorkOrder gefaWorkOrder;
	private String shortName;
	private String description;

	public GefaIncidence() {
	}

	public GefaIncidence(GefaIncidenceId id, GefaWorkOrder gefaWorkOrder) {
		this.id = id;
		this.gefaWorkOrder = gefaWorkOrder;
	}

	public GefaIncidence(GefaIncidenceId id, GefaWorkOrder gefaWorkOrder, String shortName, String description) {
		this.id = id;
		this.gefaWorkOrder = gefaWorkOrder;
		this.shortName = shortName;
		this.description = description;
	}

	public GefaIncidenceId getId() {
		return this.id;
	}

	public void setId(GefaIncidenceId id) {
		this.id = id;
	}

	public GefaWorkOrder getGefaWorkOrder() {
		return this.gefaWorkOrder;
	}

	public void setGefaWorkOrder(GefaWorkOrder gefaWorkOrder) {
		this.gefaWorkOrder = gefaWorkOrder;
	}

	public String getShortName() {
		return this.shortName;
	}

	public void setShortName(String shortName) {
		this.shortName = shortName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
