package com.eglobal.gefa.model;
// Generated 4/07/2018 10:11:17 AM by Hibernate Tools 5.0.6.Final

/**
 * GefaUser generated by hbm2java
 */
public class GefaUser implements java.io.Serializable {

	private String idUser;
	private GefaFactory gefaFactory;
	private GefaRole gefaRole;
	private String username;
	private String surname;
	private String name;
	private String email;
	private String telephone;

	public GefaUser() {
	}

	public GefaUser(String idUser, String username) {
		this.idUser = idUser;
		this.username = username;
	}

	public GefaUser(String idUser, GefaFactory gefaFactory, GefaRole gefaRole, String username, String surname,
			String name, String email, String telephone) {
		this.idUser = idUser;
		this.gefaFactory = gefaFactory;
		this.gefaRole = gefaRole;
		this.username = username;
		this.surname = surname;
		this.name = name;
		this.email = email;
		this.telephone = telephone;
	}

	public String getIdUser() {
		return this.idUser;
	}

	public void setIdUser(String idUser) {
		this.idUser = idUser;
	}

	public GefaFactory getGefaFactory() {
		return this.gefaFactory;
	}

	public void setGefaFactory(GefaFactory gefaFactory) {
		this.gefaFactory = gefaFactory;
	}

	public GefaRole getGefaRole() {
		return this.gefaRole;
	}

	public void setGefaRole(GefaRole gefaRole) {
		this.gefaRole = gefaRole;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

}
