package com.eglobal.gefa.model;
// Generated 4/07/2018 10:11:17 AM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * GefaRole generated by hbm2java
 */
public class GefaRole implements java.io.Serializable {

	private String idRole;
	private String roleName;
	private Set gefaUsers = new HashSet(0);

	public GefaRole() {
	}

	public GefaRole(String idRole) {
		this.idRole = idRole;
	}

	public GefaRole(String idRole, String roleName, Set gefaUsers) {
		this.idRole = idRole;
		this.roleName = roleName;
		this.gefaUsers = gefaUsers;
	}

	public String getIdRole() {
		return this.idRole;
	}

	public void setIdRole(String idRole) {
		this.idRole = idRole;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public Set getGefaUsers() {
		return this.gefaUsers;
	}

	public void setGefaUsers(Set gefaUsers) {
		this.gefaUsers = gefaUsers;
	}

}
