package com.eglobal.gefa.model;
// Generated 1/07/2018 07:19:37 PM by Hibernate Tools 5.0.6.Final

/**
 * TestGefa generated by hbm2java
 */
public class TestGefa implements java.io.Serializable {

	private String dummy;

	public TestGefa() {
	}

	public TestGefa(String dummy) {
		this.dummy = dummy;
	}

	public String getDummy() {
		return this.dummy;
	}

	public void setDummy(String dummy) {
		this.dummy = dummy;
	}

}
